Disable precompiled headers in CircleCI configuration
MPI, precompiled headers, and stdexec seem to conflict, leading to duplicate mangled symbols:

/usr/local/include/stdexec/__detail/__env.hpp:310:9: error: definition with same mangled name '_ZNK7stdexec5__env9get_env_tclINS_7__sexprIXtlNS_12_GLOBAL__N_1UlvE7_EEENS4_6__anonEEEEEDTcl10tag_invokeclL_ZNS_9__declvalIS1_EEOT_vEEcl9__declvalIRKS9_EEEESC
_' as another definition
        operator()(const _EnvProvider& __env_provider) const noexcept
        ^
/usr/local/include/stdexec/__detail/__env.hpp:310:9: note: previous definition is here

Since precompiled headers don't change functionality, this disables them, rather than disabling MPI
or stdexec in CI.